server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api {
        proxy_pass http://node-api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Endpoint para métricas
    location /nginx_status {
        stub_status;
        allow 0.0.0.0/0;
        deny all;
    }
}
