server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
    

    location /metrics {
        stub_status;
        access_log off;
        allow all;
    }
}

